import * as os from 'os';
import * as path from 'path';

export interface HostEntryConfig {
  user?: string;
  requestTTY?: boolean;
  forwardAgent?: boolean;
  identityFile?: string;
  additionalSshOptions?: Record<string, string>;
}

export function expandHome(input: string): string {
  if (!input) {
    return input;
  }
  if (input.startsWith('~')) {
    return path.join(os.homedir(), input.slice(1));
  }
  return input;
}

function isWrappedInQuotes(value: string): boolean {
  if (value.length < 2) {
    return false;
  }
  const first = value[0];
  const last = value[value.length - 1];
  return (first === '"' && last === '"') || (first === "'" && last === "'");
}

export function formatSshConfigValue(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return trimmed;
  }
  if (isWrappedInQuotes(trimmed)) {
    return trimmed;
  }
  if (!/[\s#"]/.test(trimmed)) {
    return trimmed;
  }
  const escaped = trimmed.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

export function buildHostEntry(
  alias: string,
  loginHost: string,
  cfg: HostEntryConfig,
  remoteCommand: string
): string {
  const lines: string[] = [];
  lines.push(`# Generated by Slurm Connect on ${new Date().toISOString()}`);
  lines.push(`Host ${alias}`);
  lines.push(`  HostName ${loginHost}`);
  if (cfg.user) {
    lines.push(`  User ${cfg.user}`);
  }
  if (cfg.requestTTY) {
    lines.push('  RequestTTY yes');
  }
  if (cfg.forwardAgent) {
    lines.push('  ForwardAgent yes');
  }
  if (cfg.identityFile) {
    const identityPath = formatSshConfigValue(expandHome(cfg.identityFile));
    lines.push(`  IdentityFile ${identityPath}`);
  }
  lines.push(`  RemoteCommand ${remoteCommand}`);

  const extraKeys = Object.keys(cfg.additionalSshOptions || {}).sort();
  for (const key of extraKeys) {
    const value = cfg.additionalSshOptions?.[key];
    if (value !== undefined && value !== null && String(value).length > 0) {
      lines.push(`  ${key} ${formatSshConfigValue(String(value))}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

export function buildTemporarySshConfigContent(entry: string, includePaths: string[]): string {
  const includeLines = includePaths.map((value) => `Include ${formatSshConfigValue(value)}`);
  const contentLines = ['# Temporary SSH config generated by Slurm Connect', entry.trimEnd()];
  if (includeLines.length > 0) {
    contentLines.push('', ...includeLines);
  }
  return `${contentLines.join('\n')}\n`;
}
