import * as os from 'os';
import * as path from 'path';

export interface HostEntryConfig {
  user?: string;
  requestTTY?: boolean;
  forwardAgent?: boolean;
  identityFile?: string;
  additionalSshOptions?: Record<string, string>;
  extraSshOptions?: string[];
}

export const SLURM_CONNECT_INCLUDE_START = '# >>> Slurm Connect (VS Code extension)';
export const SLURM_CONNECT_INCLUDE_END = '# <<< Slurm Connect';

export function expandHome(input: string): string {
  if (!input) {
    return input;
  }
  if (input.startsWith('~')) {
    const remainder = input.slice(1);
    if (!remainder) {
      return os.homedir();
    }
    if (remainder.startsWith('/') || remainder.startsWith('\\')) {
      return path.join(os.homedir(), remainder.slice(1));
    }
    return path.join(os.homedir(), remainder);
  }
  return input;
}

function isWrappedInQuotes(value: string): boolean {
  if (value.length < 2) {
    return false;
  }
  const first = value[0];
  const last = value[value.length - 1];
  return (first === '"' && last === '"') || (first === "'" && last === "'");
}

export function formatSshConfigValue(value: string): string {
  const trimmedRaw = value.trim();
  const trimmed = /^[A-Za-z]:\\/.test(trimmedRaw) ? trimmedRaw.replace(/\\/g, '/') : trimmedRaw;
  if (!trimmed) {
    return trimmed;
  }
  if (isWrappedInQuotes(trimmed)) {
    return trimmed;
  }
  if (!/[\s#"\\]/.test(trimmed) && !/^[A-Za-z]:[\\/]/.test(trimmed)) {
    return trimmed;
  }
  const escaped = trimmed.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `"${escaped}"`;
}

export function buildHostEntry(
  alias: string,
  loginHost: string,
  cfg: HostEntryConfig,
  remoteCommand: string
): string {
  const lines: string[] = [];
  lines.push(`# Generated by Slurm Connect on ${new Date().toISOString()}`);
  lines.push(`Host ${alias}`);
  lines.push(`  HostName ${loginHost}`);
  if (cfg.user) {
    lines.push(`  User ${cfg.user}`);
  }
  if (cfg.requestTTY) {
    lines.push('  RequestTTY yes');
  }
  if (cfg.forwardAgent) {
    lines.push('  ForwardAgent yes');
  }
  if (cfg.identityFile) {
    const identityPath = formatSshConfigValue(expandHome(cfg.identityFile));
    lines.push(`  IdentityFile ${identityPath}`);
  }
  lines.push(`  RemoteCommand ${remoteCommand}`);

  const extraKeys = Object.keys(cfg.additionalSshOptions || {}).sort();
  for (const key of extraKeys) {
    const value = cfg.additionalSshOptions?.[key];
    if (value !== undefined && value !== null && String(value).length > 0) {
      lines.push(`  ${key} ${formatSshConfigValue(String(value))}`);
    }
  }

  const extraLines = cfg.extraSshOptions || [];
  for (const line of extraLines) {
    const trimmed = line.trim();
    if (!trimmed) {
      continue;
    }
    lines.push(`  ${trimmed}`);
  }

  return `${lines.join('\n')}\n`;
}

export function buildTemporarySshConfigContent(entry: string, includePaths: string[]): string {
  const includeLines = includePaths.map((value) => `Include ${formatSshConfigValue(value)}`);
  const contentLines = ['# Temporary SSH config generated by Slurm Connect', entry.trimEnd()];
  if (includeLines.length > 0) {
    contentLines.push('', ...includeLines);
  }
  return `${contentLines.join('\n')}\n`;
}

export function buildSlurmConnectIncludeBlock(includePath: string): string {
  const includeLine = `Include ${formatSshConfigValue(includePath)}`;
  const lines = [
    SLURM_CONNECT_INCLUDE_START,
    '# This Include is managed by the Slurm Connect extension.',
    '# Remove this block to stop injecting Slurm Connect hosts.',
    includeLine,
    SLURM_CONNECT_INCLUDE_END
  ];
  return lines.join('\n');
}

export function buildSlurmConnectIncludeContent(entry: string): string {
  const contentLines = ['# Slurm Connect SSH hosts', entry.trimEnd()];
  return `${contentLines.join('\n')}\n`;
}
